CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(25) NOT NULL,
    uri VARCHAR(30) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);